version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "uv"
    directory: "/libs/genai"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "uv"
    directory: "/libs/vertexai"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "uv"
    directory: "/libs/community"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
