name: "🐛 Bug Report"
description: Report a bug
labels: ["bug"]
type: bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        ## Important Links
        - [Documentation](https://docs.langchain.com/oss/python/integrations/providers/google)
        - [API Reference](https://reference.langchain.com/python/integrations/langchain_google/)

  - type: checkboxes
    id: package
    attributes:
      label: Package (Required)
      description: Which package(s) is this bug related to? **Please select at least one**
      options:
        - label: langchain-google-genai
        - label: langchain-google-vertexai
        - label: langchain-google-community
        - label: Other / not sure / general

  - type: checkboxes
    attributes:
      label: Checked other resources
      description: Please confirm you have done the following before submitting
      options:
        - label: I added a descriptive title to this issue
          required: true
        - label: I searched the LangChain documentation and API reference (linked above)
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it
          required: true
        - label: I am sure this is a bug and not a question or request for help
          required: true

  - type: textarea
    attributes:
      label: Example Code (Python)
      description: |
        Please provide a minimal, reproducible code example that demonstrates the bug.
        Without this, we may not be able to investigate the issue.
        (This will be automatically formatted into code, so no need for backticks.)
      render: python
      placeholder: |
        from langchain_google_genai import ChatGoogleGenerativeAI
        # or from langchain_google_vertexai import ChatVertexAI
        # or from langchain_google_community import ...

        # Your example here
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please copy and paste the full error message and
        stack trace.
        (This will be automatically formatted into code, so no need for backticks.)
      render: shell

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe what you're doing (e.g. how you encountered this bug), what you expect to happen, and what actually happens.

        Please be as detailed as possible. The more information you provide, the easier it will be to help you.
      placeholder: |
        1. What were you trying to do?
        2. What did you expect to happen?
        3. What actually happened?
    validations:
      required: true
